baseURL: 'https://swlacy.com'
languageCode: en-us
title: Sid's Blog
theme: PaperMod
paginate: 5

minify:
  disableXML: true
  minifyOutput: true

menu:
    main:
      - name: Home
        url: /
        weight: 1
      - name: Documents
        url: /documents
        weight: 2
      - name: Posts
        url: /posts
        weight: 3
      - name: Resume
        url: /resume.pdf
        weight: 4
      - name: About
        url: /about
        weight: 5
      - name: Archive
        url: /archive
        weight: 6
      - name: Search
        url: /search
        weight: 7

params:
    env: production
    defaultTheme: light
    ShowReadingTime: true
    ShowBreadCrumbs: true
    ShowCodeCopyButtons: true
    ShowShareButtons: true
    author: ["Sid Lacy"]

    assets:
        favicon: "favicon.ico"
        favicon16x16: "favicon-16x16.png"
        favicon32x32: "favicon-32x32.png"
        apple_touch_icon: "apple-touch-icon.png"

    profileMode:
        enabled: true
        title: "Hi, my name is Sid."
        subtitle: "I write about computer security."
        imageUrl: "https://avatars.githubusercontent.com/u/77074184"
        imageTitle: "Sid Lacy"
        imageWidth: 196
        imageHeight: 196
        buttons:
            - name: Documents
              url: "/documents"
            - name: Blog Posts
              url: "/posts"
            - name: "Featured: Fishing for Malware"
              url: "/posts/fishing-for-malware"
            - name: "Featured: HTB Previse Report"
              url: "/documents/previse"

    socialIcons:
        - name: "github"
          url: "https://github.com/lacysw"
        - name: "linkedin"
          url: "https://www.linkedin.com/in/lacysw/"
        - name: "email"
          url: "mailto:contact@swlacy.com?subject=Hello!"

    cover:
        linkFullImages: true

outputs:
    home:
        - HTML
        - RSS
        - JSON
