baseURL: 'https://swlacy.com'
languageCode: en-us
title: Sid's Blog
theme: PaperMod
paginate: 15
enableRobotsTXT: true

googleAnalytics: G-QFRYSRDLC1

minify:
  disableXML: true
  minifyOutput: true

menu:
    main:
      - name: Docs
        url: /documents
        weight: 1
      - name: Blog
        url: /posts
        weight: 2
      - name: Resume
        url: /resume.pdf
        weight: 3
      - name: About
        url: /about
        weight: 4
      - name: Archive
        url: /archive
        weight: 5
      - name: Search
        url: /search
        weight: 6

params:
    title: "Sid's Blog"
    Description: "I write about computer security"
    keywords: [Sid, Lacy, Blog, Security, Cybersecurity, Computer, HackTheBox, Project, Career, Resume, GitHub, LinkedIn, Site]
    env: production
    defaultTheme: light
    ShowReadingTime: true
    ShowBreadCrumbs: true
    ShowCodeCopyButtons: true
    ShowShareButtons: true
    author: ["Sid Lacy"]

    label:
        icon: apple-touch-icon.png

    assets:
        favicon: "favicon.ico"
        favicon16x16: "favicon-16x16.png"
        favicon32x32: "favicon-32x32.png"
        apple_touch_icon: "apple-touch-icon.png"

    profileMode:
        enabled: true
        title: "Hi, my name is Sid."
        subtitle: "I write about computer security."
        imageUrl: "headshot.png"
        imageTitle: "Sid Lacy"
        imageWidth: 196
        imageHeight: 196
        buttons:
            - name: Documents
              url: "/documents"
            - name: Blog Posts
              url: "/posts"
            - name: "Featured: Fishing for Malware"
              url: "/posts/fishing-for-malware-1"
            - name: "Featured: HTB Previse Report"
              url: "/documents/previse"

    socialIcons:
        - name: "email"
          url: "mailto:contact@swlacy.com?subject=Hello!"
        - name: "github"
          url: "https://github.com/lacysw"
        - name: "linkedin"
          url: "https://www.linkedin.com/in/lacysw/"
        - name: "hackthebox"
          url: "https://app.hackthebox.com/profile/787255"
        - name: "wwucyber"
          url: "https://wwucyber.com"

    cover:
        linkFullImages: true

    fuseOpts:
        isCaseSensitive: false
        shouldSort: true
        location: 0
        distance: 1000
        threshold: 0.4
        minMatchCharLength: 0
        keys: ["title", "permalink", "summary", "content"]

outputs:
    home:
        - HTML
        - RSS
        - JSON
