baseURL: 'https://swlacy.com'
languageCode: en-us
title: Sid's Blog
theme: PaperMod
paginate: 15
enableRobotsTXT: true

googleAnalytics: G-QFRYSRDLC1

PygmentsCodeFences: true
PygmentsStyle: "monokai"

minify:
  disableXML: true
  minifyOutput: true

menu:
    main:
      - name: Blog
        url: /posts
        weight: 1
      - name: Docs
        url: /documents
        weight: 2
      - name: Resume
        url: /resume
        weight: 3
      - name: About
        url: /about
        weight: 4
      - name: Archive
        url: /archive
        weight: 5
      - name: Search
        url: /search
        weight: 6

params:
    title: "Sid's Blog"
    Description: "I write about computer security"
    keywords: [Sid, Lacy, Blog, Security, Cybersecurity, Computer, HackTheBox, Project, Career, Resume, GitHub, LinkedIn, Site]
    env: production
    defaultTheme: auto
    ShowReadingTime: true
    ShowBreadCrumbs: true
    ShowCodeCopyButtons: true
    ShowShareButtons: true
    author: ["Sid Lacy"]

    label:
        icon: apple-touch-icon.png

    assets:
        favicon: "favicon.ico"
        favicon16x16: "favicon-16x16.png"
        favicon32x32: "favicon-32x32.png"
        apple_touch_icon: "apple-touch-icon.png"

    profileMode:
        enabled: true
        title: "Hi, my name is Sid."
        subtitle: "Welcome to my website — I'm glad you're here. I ramble about computer security and technology. Feel free to take a look!"
        imageUrl: "/media/headshot.png"
        imageTitle: "Sid Lacy"
        imageWidth: 196
        imageHeight: 196
        buttons:
            - name: ""
              url: ""

    socialIcons:
        - name: "Email"
          url: "mailto:contact@swlacy.com?subject=Hello!"
        - name: "Twitter"
          url: "https://twitter.com/actuallysid"
        - name: "LinkedIn"
          url: "https://www.linkedin.com/in/lacysw/"
        - name: "GitHub"
          url: "https://github.com/lacysw"


    cover:
        linkFullImages: true

    fuseOpts:
        isCaseSensitive: false
        shouldSort: true
        location: 0
        distance: 1000
        threshold: 0.4
        minMatchCharLength: 0
        keys: ["title", "permalink", "summary", "content"]

outputs:
    home:
        - HTML
        - RSS
        - JSON
